### ISSUE TITLE
Adding Vuetify

### ISSUE THREAD

**Issue by githubr** [danijelh/aspnetcore-vue-typescript-template#10]
Hi @danijelh would you mind to show me how I add Vuetify in the project? Thanks.

**Comment by danijelh** [comment]
Hi 👋,

it should be pretty straightforward.

**1. Install the pacakge**

Run `npm install vuetify --save `

**2. Reference vuetify .css**

In `site.css` change the following lines
```
// @import "~bulmaswatch/flatly/bulmaswatch.scss"; // Comment out Bulma
@import "~vuetify/dist/vuetify.min.css"; // Add vuetify css 
```

**3. Add vuetify in modules** 

So in modules where you want to use Vuetify you add the following lines
```
import Vuetify from 'vuetify'
Vue.use(Vuetify)
```

That's it. Also, don't forget to wrap the HTML in `<v-app>` tags before using the framework components.

Also also, take note that since Vuetify is a complete framework it's maybe not best suited for the multipage applications. But, by all means, you can use it in your modules and it will work the same as in the project with Vue CLI.

**Comment by githubr** [comment]
Thanks @danijelh. I really appreciate that.

Could you please explain a bit more about Vuetify probably is not the best for multipage application? Will it be performance wise or harder to work with or something else?

**Comment by danijelh** [comment]
No, it will work just fine and as any multi-page application. What I meant to say is that Vuetify itself was designed to be used primarily in a SPA but since every module is a SPA for itself you'll find yourself with multiple spa's and multiple Vuetify imports. It's just organizational thingy, something like using multiple Angular applications within the same application but on a much lower scale. Anyway, you're fine with Vuetify, regarding performance and usage everything is ok.

**Comment by githubr** [comment]
Thanks @danijelh. You can close this issue if you want. I have been able to add Vuetify to my .net project.

**Comment by danijelh** [comment]
Gr8! Happy developing 👍
