### ISSUE TITLE
Localization integration

### ISSUE THREAD

**Issue by jkgh2018** [danijelh/aspnetcore-vue-typescript-template#11]
Could you give an example of how to localize the client apps?
I'm using 'ResxToJson' nuget package to convert resx files to i18n format via a build task, but how would I then integrate the generated Javascript into the client.
Do you suggest putting the i18n files into the common folder, or have one i18n file per app? I would like to integrate 'vue-i18n'.
https://kazupon.github.io/vue-i18n/

thanks in advance!

**Comment by danijelh** [comment]
👋, 

I personally would have 1 file per module because it makes it easier to maintain and leads to fewer conflicts. But, what you might encounter is that you'll find yourself duplicating strings as `Save`, `Cancel` etc ( random words on top of my head ) so it might be a good idea to also have a common dictionary. 

Regarding the `vue-i18n`, you'll have to setup/import translations in every module since every module has a life of its own. 

So, import common translations + module translations and hook them up on your Vue instance in every module. The rest should be the same as in the docs of the package.

**Comment by jkgh2018** [comment]
Thank you - I have got it working now with the following approach:
- .net core project: add a Resources folder with the .resx files
- .net core project: add a build step to use Powershell to convert the .resx to i18n JSON files & save to the Client app common folder
- client project: use 'vue-i18n' per its instructions and inject into each Vue app
