### ISSUE TITLE
Question Please, Is it possible to use react in same project?

### ISSUE THREAD

**Issue by nigel-dewar** [danijelh/aspnetcore-vue-typescript-template#18]
Hi Daniel,

I love this repo. I keep coming back to it because I find it so interesting.

I have a question for you please,

Do you think its possible to combine react together in this project? Or would it make the Webpack config tooooo crazy?

Did you ever experiment with using a central store? maybe using LocalStorage hooked up to Vuex so the different isolated Vue apps could still talk to each other? Maybe to do this there would need to be some kind of eventing system which is shared between the different SPAs I suppose?

Your Answers would be very much appreciated If you have the time

Kind Regards

**Comment by danijelh** [comment]
Hi @nigel-dewar ,

first, thank you for the support, I'm glad this repo is of help to you.

To answer your questions. 

- I don't believe adding React support would complicate things too much. It should be a minor change of adding support for **jsx** and including additional entry files.
- Since transition between multiple SPA's includes page refresh, you are right, store data should be persisted. You are on the right track, best way I see to implement persisted storage without going to the API for the data is to **SAVE** and **READ** from the storage first.

Sorry for the late reply.

Happy developing 🚀
